HuckHack/Controllers/CommunicationController.cs
using HuckHack.Domain.Contracts.Repositories;
using HuckHack.Domain.Contracts.Services;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using System.Threading.Tasks;

// For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860

namespace HuckHack.Controllers
{
    [Authorize]
    public class CommunicationController : Controller
    {
        private readonly IUserRepository _userRepository;
        private readonly ICommunicationService _communicationService;

        public CommunicationController(
            IUserRepository userRepository, 
            ICommunicationService communicationService)
        {
            _userRepository = userRepository;
            _communicationService = communicationService;
        }

        public async Task<IActionResult> SendInviteRequest(InviteRequestViewModel model)
        {
            var userFrom = _userRepository.GetByEmail(User.Identity.Name);

            if (userFrom.SendedInviteRequests.Contains(model.To))
                return Conflict();

            userFrom.SendedInviteRequests.Add(model.To);
            _userRepository.Update(userFrom);

            var userTo = _userRepository.Get(model.To);
            //var profileLink = $"huckhack.com/Profile/{userFrom.Id}";
            var profileLink = $"http://localhost:5000/Teams/JoinToTeam?teamId={model.TeamId}";

            await _communicationService.SendInviteEmail(userFrom.ShortDisplayName, profileLink, userTo.Email, model.CoverMessage);
            return Ok();
        }
    }

    public class InviteRequestViewModel
    {
        public string To { get; set; }

        public string CoverMessage { get; set; }

        public string TeamId { get; set; }
    }
}

HuckHack/Controllers/TeamsController.cs
using HuckHack.Domain.Contracts.Repositories;
using HuckHack.Domain.Contracts.Services;
using HuckHack.Domain.Entities;
using HuckHack.Domain.Services;
using HuckHack.Extensions;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace HuckHack.Controllers
{
    [Authorize]
    public class TeamsController : Controller
    {
        private readonly IEventRepository _eventRepository;
        private readonly ITeamCardRepository _teamCardRepository;
        private readonly IUserRepository _userRepository;
        private readonly ITeamRepository _teamRepository;
        private readonly IApplicationRepository _applicationRepository;
        private readonly ITeamService _teamService;

        public TeamsController(
            IEventRepository eventRepository,
            ITeamCardRepository teamCardRepository,
            IUserRepository userRepository,
            ITeamRepository teamRepository,
            IApplicationRepository applicationRepository, 
            ITeamService teamService)
        {
            _eventRepository = eventRepository;
            _teamCardRepository = teamCardRepository;
            _userRepository = userRepository;
            _teamRepository = teamRepository;
            _applicationRepository = applicationRepository;
            _teamService = teamService;
        }

        [HttpPost]
        public IActionResult Create(Team team)
        {
            _teamService.Create(team, User.GetId());
            return RedirectToAction("Index", "Profile");
        }

        [HttpGet]
        public IActionResult JoinToTeam(string teamId)
        {
            _teamService.AddToTeam(teamId, User.GetId());
            return RedirectToAction("Application", new { id = teamId });
        }

        [HttpPost]
        public IActionResult CreateTeam(Team team)
        {
            var id = _teamService.Create(team, User.GetId());
            return RedirectToAction("Application", new { id = id });
        }

        [HttpGet]
        public IActionResult Application(string id)
        {
            //var application = _applicationRepository.Get(id);
            //return View("~/Views/Applications/Application.cshtml", application);
            var team = _teamRepository.Get(id);
            team.Users = _teamService.GetTeamUsers(id);
            return View("~/Views/Applications/Application.cshtml", team);
        }

        [HttpGet]
        public IActionResult ApplicationList(string eventId)
        {
            //var applications = _applicationRepository.GetByEventId(eventId);
            //return View("~/Views/Applications/List.cshtml", applications);
            var teams = _teamRepository.Get(i => i.EventId, eventId);
            return View("~/Views/Applications/List.cshtml", teams);
        }

        [HttpGet]
        public Team Get(string id) => _teamRepository.Get(id);
    }
}

HuckHack/Views/Shared/Modals/CreateApplicationModalPartial.cshtml
@using HuckHack.Domain.Entities

<div class="modal fade" id="addApplicationModal" tabindex="-1" role="dialog" aria-labelledby="addApplicationModal"
     aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="addApplicationModalLabel"></h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <form asp-controller="Teams" asp-action="CreateTeam" enctype="multipart/form-data" method="post" class="">
                <div class="modal-body md-form">

                    <div class="md-form col-12">
                        <div class="row">
                            <div class="col-11">
                                <input id="teamNameInput" name="Name" class="form-control" type="text" placeholder="Имя команды" />
                            </div>
                            <div class="col-1">
                                <i class="fas fa-question-circle pt-2 tooltip-container" data-toggle="tooltip" data-placement="top" title="Не обязательно писать такое, как будет на хаке"></i>
                            </div>
                        </div>
                    </div>


                    <div class="md-form col-12">
                        <div class="row">
                            <div class="col-11">
                                <input id="shortDescriptionInput" name="ShortDescription" class="form-control" type="text" placeholder="Краткое описание(макс. 200 символов)" />
                            </div>
                            <div class="col-1">
                                <i class="fas fa-question-circle pt-2 tooltip-container" data-toggle="tooltip" data-placement="top" title="Рекомендуем написать стек, трек и вакантную роль"></i>
                            </div>
                        </div>

                    </div>
                    <div class="md-form col-12">

                        <div class="row">
                            <div class="col-11">
                                <textarea id="fullDescriptionInput" name="FullDescription" class="form-control md-textarea" placeholder="Полное описание"></textarea>
                            </div>
                            <div class="col-1">
                                <i class="fas fa-question-circle pt-2 tooltip-container" data-toggle="tooltip" data-placement="top" title="Для уточнения деталей, можно также оставить контактные данные"></i>
                            </div>
                        </div>
                    </div>
                    <input type="hidden" name="EventId" value="@ViewBag.EventId">
                    <input type="hidden" name="EventName" value="@ViewBag.EventName">
                </div>
                <div class="modal-footer">
                    <button type="submit" class="btn btn-primary btn-rounded">
                        <span>
                            Создать
                            <i class="fas fa-cloud-upload-alt ml-3" aria-hidden="true"></i>
                        </span>
                    </button>
                </div>
            </form>
        </div>
    </div>
</div>

HuckHack/Views/Shared/Modals/CreateHackerCardModalPartial.cshtml
@using HuckHack.Domain.Entities
<div class="modal fade" id="addHackerCardModal" tabindex="-1" role="dialog" aria-labelledby="addHackerCardModalLabel"
     aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="addHackerCardModalLabel"></h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <form asp-controller="HackerCards" asp-action="Create" enctype="multipart/form-data" method="post" class="">
                <div class="modal-body md-form">

                    @*<div class="row">
            <div class="md-form col-6">
                <input id="firstNameInput" name="FirstName" value="@ViewBag.User.FirstName" class="form-control" type="text" />
                <label for="firstNameInput">First name</label>
            </div>
            <div class="md-form col-6">
                <input id="lastNameInput" name="LastName" value="@ViewBag.User.LastName" class="form-control" type="text" />
                <label for="lastNameInput">Last name</label>
            </div>
        </div>*@

                    <div class="md-form col-12">
                        <div class="row">
                            <div class="col-11">
                                <input id="descriptionInput" name="Description" class="form-control" type="text" placeholder="В трех словах о себе" />
                            </div>
                            <div class="col-1">
                                <i class="fas fa-question-circle pt-2 tooltip-container" data-toggle="tooltip" data-placement="top" title="Рекомендуем написать желаемый стек, трек и роль"></i>
                            </div>
                        </div>

                    </div>
                    <input type="hidden" name="EventId" value="@ViewBag.EventId">

                </div>
                <div class="modal-footer">
                    <button type="submit" class="btn btn-primary btn-rounded">
                        <span>
                            Создать
                            <i class="fas fa-cloud-upload-alt ml-3" aria-hidden="true"></i>
                        </span>
                    </button>
                </div>
            </form>
        </div>
    </div>
</div>

HuckHack/Views/Shared/Modals/CreateTeamModalPartial.cshtml
@using HuckHack.Domain.Entities
<div class="modal fade" id="createTeamModal" tabindex="-1" role="dialog" aria-labelledby="createTeamModalLabel"
     aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="createTeamModalLabel">Создание команды</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <form asp-controller="Teams" asp-action="Create" enctype="multipart/form-data" method="post" class="">
                <div class="modal-body md-form">
                    
                    <div class="md-form col-6">
                        <input id="nameInput" name="Name" class="form-control" type="text" />
                        <label for="nameInput">Название команды</label>
                    </div>

                    <div class="md-form col-6">
                        <input id="membersCountInput" name="MembersCount" class="form-control" type="text" />
                        <label for="membersCountInput">Количество участников</label>
                    </div>

                    <div class="md-form col-6">
                        <textarea id="descriptionInput" name="Description" class="md-textarea form-control" rows="3" type="text"></textarea>
                        <label for="descriptionInput">Описание</label>
                    </div>
                </div>
                <div class="modal-footer">
                    <button type="submit" class="btn btn-primary btn-rounded">
                        <span>
                            Создать
                            <i class="fas fa-cloud-upload-alt ml-3" aria-hidden="true"></i>
                        </span>
                    </button>
                </div>
            </form>
        </div>
    </div>
</div>

HuckHack/Views/Shared/Modals/InviteRequestModal.cshtml
@using HuckHack.Domain.Entities
<div class="modal fade" id="InviteRequestModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel"
     aria-hidden="true">

    <div class="modal-dialog modal-sm" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h4 class="modal-title w-150" id="myModalLabel">Отправить приглашение</h4>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <form asp-controller="Communication" asp-action="SendInviteRequest">

                <input type="hidden" id="inviteTo" name="To">
                <div class="modal-body">
                    <div class="md-form form-sm m-2">
                        <textarea style="resize: none" class="md-textarea form-control" rows="3" name="CoverMessage" id="CoverMessage"></textarea>
                        <label for="CoverMessage">Сообщение</label>
                    </div>
                </div>

                <select class="md-form mdb-select form-sm m-4" name="TeamId">
                    <option value="" disabled="">В какую команду</option>
                    @foreach (var team in ViewBag.GuestTeams ?? new List<Team>())
                    {
                        <option value="@team.Id">@team.Name (@team.EventName)</option>
                    }
                </select>

                <div class="modal-footer">
                    <input type="submit" class="btn btn-primary btn-sm btn-rounded" value="Отправить" />
                </div>
            </form>
        </div>
    </div>
</div>

<script type="text/javascript">
    $(function () {
        $('#InviteRequestModal form').submit(function (e) {
            var $form = $(this);
            $.ajax({
                type: $form.attr('method'),
                url: $form.attr('action'),
                data: $form.serialize()
            }).done(function () {
                $('#InviteRequestModal').modal("hide");
            }).fail(function () {
                alert('fail');
            });
            //отмена действия по умолчанию для кнопки submit
            e.preventDefault();
        });
    });
    $('#InviteRequestModal').on('show.bs.modal', function (event) {
        var button = $(event.relatedTarget);
        var toId = button.data('to');
        var modal = $(this);
        modal.find('#inviteTo').val(toId);
    })
</script>