HuckHack/Controllers/EventsController.cs
using HuckHack.Domain.Contracts.Repositories;
using HuckHack.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using System.Collections.Generic;

namespace HuckHack.Controllers
{
    [Authorize]
    public class EventsController : Controller
    {
        private readonly IEventRepository _eventRepository;

        public EventsController(
            IEventRepository eventRepository)
        {
            _eventRepository = eventRepository;
        }

        public IActionResult Index()
        {
            var model = new EventsViewModel
            {
                Items = _eventRepository.Get(),
                Cities = new List<string> { "Москва", "Санкт-Петербург","Казань", "Нижний Новгород"}
            };

            model.Items.Sort((i, j) => (i.StartDate >= j.StartDate ? -1 : 1));

            return View(model);
        }

        [Route("Event/{id}")]
        public IActionResult Index(string id)
        {
            var ev = _eventRepository.Get(id);
            ViewBag.EventId = id;
            ViewBag.EventName = ev.Name;
            return View("Event", ev);
        }
    }
}

HuckHack/Controllers/TeamsController.cs
using HuckHack.Domain.Contracts.Repositories;
using HuckHack.Domain.Contracts.Services;
using HuckHack.Domain.Entities;
using HuckHack.Domain.Services;
using HuckHack.Extensions;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace HuckHack.Controllers
{
    [Authorize]
    public class TeamsController : Controller
    {
        private readonly IEventRepository _eventRepository;
        private readonly ITeamCardRepository _teamCardRepository;
        private readonly IUserRepository _userRepository;
        private readonly ITeamRepository _teamRepository;
        private readonly IApplicationRepository _applicationRepository;
        private readonly ITeamService _teamService;

        public TeamsController(
            IEventRepository eventRepository,
            ITeamCardRepository teamCardRepository,
            IUserRepository userRepository,
            ITeamRepository teamRepository,
            IApplicationRepository applicationRepository, 
            ITeamService teamService)
        {
            _eventRepository = eventRepository;
            _teamCardRepository = teamCardRepository;
            _userRepository = userRepository;
            _teamRepository = teamRepository;
            _applicationRepository = applicationRepository;
            _teamService = teamService;
        }

        [HttpPost]
        public IActionResult Create(Team team)
        {
            _teamService.Create(team, User.GetId());
            return RedirectToAction("Index", "Profile");
        }

        [HttpGet]
        public IActionResult JoinToTeam(string teamId)
        {
            _teamService.AddToTeam(teamId, User.GetId());
            return RedirectToAction("Application", new { id = teamId });
        }

        [HttpPost]
        public IActionResult CreateTeam(Team team)
        {
            var id = _teamService.Create(team, User.GetId());
            return RedirectToAction("Application", new { id = id });
        }

        [HttpGet]
        public IActionResult Application(string id)
        {
            //var application = _applicationRepository.Get(id);
            //return View("~/Views/Applications/Application.cshtml", application);
            var team = _teamRepository.Get(id);
            team.Users = _teamService.GetTeamUsers(id);
            return View("~/Views/Applications/Application.cshtml", team);
        }

        [HttpGet]
        public IActionResult ApplicationList(string eventId)
        {
            //var applications = _applicationRepository.GetByEventId(eventId);
            //return View("~/Views/Applications/List.cshtml", applications);
            var teams = _teamRepository.Get(i => i.EventId, eventId);
            return View("~/Views/Applications/List.cshtml", teams);
        }

        [HttpGet]
        public Team Get(string id) => _teamRepository.Get(id);
    }
}

HuckHack/Views/Applications/Application.cshtml
@model HuckHack.Domain.Entities.Team

<div class="container">
    <div class="row">
        <div class="col-12 ">
            <div class="card p-3">
                <div class="row">
                    <div class="col-12 event-header">
                        <h1>@Model.Name</h1>
                        @*<h2>@Model.Description</h2>*@
                    </div>
                </div>
                <hr />
            </div>
        </div>
    </div>
    <div class="row">
        <div class="col-9 p-3">
            <div class="card p-5">
                <p>@Model.ShortDescription</p>
            </div>
            
            <div class="card card-cascade cascading-admin-card user-card mt-3 text-center mb-2">
                <div class="card-header py-3">
                    <h3 style="color: gray;">Участники</h3>
                </div>
            </div>

            @foreach (var hacker in Model.Users)
            {
                <div class="card mt-2">
                    <div class="card-body">
                        <div class="row">
                            <div class="col-lg-3 d-flex mb-2 align-items-center">
                                <div class="avatar white d-flex justify-content-center align-items-center">
                                    <img src="@(!string.IsNullOrEmpty(hacker.Picture) ? "data:image/gif;base64, " + hacker.Picture :
                                                  "https://www.expert-comptable-sogar.fr/files/img/article.jpg")" class="rounded-circle img-fluid z-depth-1" alt="woman avatar">
                                </div>
                            </div>
                            <div class="col-lg-9">
                                <div class="row">
                                    <p class="col-3 font-weight-bold lead">
                                        <a asp-controller="Profile" asp-action="Index" asp-route-id="@hacker.Id"><strong>@hacker.ShortDisplayName</strong></a>
                                    </p>
                                    <span class="col-3" style="color: gray;"><i class="fas fa-tag"></i> @hacker.Specialty</span>
                                </div>
                                <div class="row">
                                    <p class="col-auto font-weight-bold text-muted mt-1">Навыки </p>
                                    <div>
                                        @foreach (var skill in string.IsNullOrEmpty(hacker.HardSkills) ? new List<string>() : hacker.HardSkills.Split(' ').ToList())
                                        {
                                            <div class="chip">
                                                @skill
                                            </div>
                                        }
                                    </div>
                                </div>

                                <p class="text-muted font-weight-light">
                                    @hacker.HackathonsExperience
                                </p>
                            </div>

                        </div>
                    </div>
                </div>
            }

        </div>
        <div class="col-3 p-3">
            <div class="card mb-2 text-center">
                <div class="card-body">
                    <a asp-controller="Events" asp-action="Index" asp-route-id="@Model.EventId" class="btn btn-primary btn-lg active" role="button" aria-pressed="true">К хакатону</a>
                    <a asp-controller="Profile" asp-action="Index" asp-route-id="@Model.UserId" class="btn btn-default btn-lg active" role="button" aria-pressed="true">К капитану</a>
                </div>
            </div>
        </div>
    </div>
</div>

HuckHack/Views/Applications/List.cshtml
@using HuckHack.Domain.Entities
@using HuckHack.Extensions
@model IEnumerable<HuckHack.Domain.Entities.Team>

<div class="container mt-1">
    <div class="row mb-3">
        <div class="col-3">
            <div class="card p-3">
                <div class="row">
                    <div class="card-body">
                        @*<div class="col-lg-3">
                                <select id="cityFilter" onchange="filterByCity()" class="mdb-select md-form" searchable="Искать...">
                                    <option value="Any" disabled selected>Место проведения</option>
                                    <option value="Any">Любое</option>
                                    @foreach (var city in Model.Cities)
                                    {
                                        <option value="@city">@city</option>
                                    }
                                </select>
                            </div>*@

                        <div class="col-lg-3">
                            <label>Только мои команды</label>
                            <div class="switch">
                                <label>
                                    Выкл.
                                    <input id="onlyUserTeams" type="checkbox" unchecked>
                                    <span class="lever"></span> Вкл.
                                </label>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>

        <div class="col-9">
            @if (Model == null || Model.Count() == 0)
            {
                <div class="mt-3">Пусто :(</div>
            }
            else
            {
                @foreach (var team in Model)
                {
                    @*<div class="card team-card  @(applicationToFindHackers.UserId == User.GetId() ? "" : "notUserTeam")">
                    <div class="card-body">
                        <div class="row">
                            <div class="col-lg-3 d-flex mb-2 align-items-center">
                                <div class="avatar w-50 white d-flex justify-content-center align-items-center">
                                    <img src="https://www.expert-comptable-sogar.fr/files/img/article.jpg" class="rounded-circle img-fluid z-depth-1" alt="woman avatar">
                                </div>
                            </div>
                            <div class="col-lg-9">
                                <div class="row">
                                    <p class="col-2 font-weight-bold lead"><strong>@applicationToFindHackers.TeamName</strong></p>
                                    <a asp-controller="Teams" asp-action="Application" asp-route-id="@applicationToFindHackers.Id" class="col-2 btn btn-default btn-rounded btn-sm">Просмотр</a>
                                </div>

                                <p class="text-muted font-weight-light">
                                    @applicationToFindHackers.ShortDescription
                                </p>
                            </div>

                        </div>
                    </div>
                </div>*@

                    <div class="card mb-2">
                        <div class="card-body">
                            <div class="row">
                                <div class="col-lg-3 d-flex mb-2 align-items-center">
                                    <div class="avatar white d-flex justify-content-center align-items-center">
                                        <img src="https://www.expert-comptable-sogar.fr/files/img/article.jpg" class="rounded-circle img-fluid z-depth-1" alt="woman avatar">
                                    </div>
                                </div>
                                <div class="col-lg-9 text-left">
                                    <div class="row">
                                        <p class="col-12 font-weight-bold lead">
                                            <span class="badge badge-pill light-blue"><i class="fas fa-users" aria-hidden="true"></i></span>
                                            <strong><a href="Application?id=@team.Id">@team.Name</a></strong>
                                        </p>
                                    </div>

                                    <div class="row">
                                        <p class="col-12 font-weight-light lead">
                                            <span class="badge badge-pill light-blue"><i class="fas fa-laptop-code" aria-hidden="true"></i></span>
                                            @*<strong><a href="Events/@team.EventId">MegaHack</a></strong>*@
                                            <strong><a asp-controller="Events" asp-action="Index" asp-route-id="@team.EventId">@team.EventName</a></strong>
                                        </p>
                                    </div>

                                    <p class="text-muted font-weight-light card-text">
                                        @team.ShortDescription
                                    </p>

                                    <hr class="my-1 pb-2">
                                    <div class="row">
                                        <span class="col-2 ml-3 badge badge-pill badge-success">Состав: @(team.UserIds.Count)</span>
                                    </div>
                                </div>

                            </div>
                        </div>
                    </div>
                }
            }
        </div>
    </div>
</div>

<script>
    $("#onlyActual").click(function () {
        applyFilter();
    });

    function applyFilter() {
        $(".team-card").show();

        var onlyUserTeams = $("#onlyUserTeams").prop('checked');

        if (onlyUserTeams) {
            $(".notUserTeam").hide();
        }
    }
</script>